name = "GymnasiumWrapper"
uuid = "797ab718-28a9-47c1-bed6-0b1d71275744"
authors = ["Powers, Joshua <dev@powerslabs.org>"]
version = "0.1.0"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
julia = "1.11"
Conda = "1.9"
PyCall = "1.96"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
